version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"  # Adjust the port according to your application
    environment:
      - BOOK_STORE_DATABASE_URI=mongodb://bookstore_user:bookstore_password@mongodb:27017/bookstore?authSource=admin
    depends_on:
      - mongodb
    networks:
      - bookstore-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bookstore_user
      - MONGO_INITDB_ROOT_PASSWORD=bookstore_password
      - MONGO_INITDB_DATABASE=bookstore
    volumes:
      - mongodb_data:/data/db
    networks:
      - bookstore-network

networks:
  bookstore-network:
    driver: bridge

volumes:
  mongodb_data:
